apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-eks-cluster
  region: us-east-1
  version: "1.27"
  tags:
    Environment: dev
    Owner: devops

nodeGroups:
  - name: app-nodegroup
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albIngress: true
        cloudWatch: true