apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: quiz
type: Opaque
data:
  mongo-username: YWRtaW4=
  mongo-password: cGFzc3dvcmQxMjM=
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvLXNlcnZpY2UucXVpei5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9hcHBfZGI/YXV0aFNvdXJjZT1hZG1pbg==


# mongodb://admin:password123@mongo-service.quiz.svc.cluster.local:27017/app_db?authSource=admin